Revert "Update e2_procfs_bus.c"
fatal error: media/dvbdev.h: No such file or directory
|  #include <media/dvbdev.h>

This reverts commit e6cbd9464a45486d6952ce1f17970016baa7d282.